MODEL:


TRAIN:
  logger_dir: './logger/'
  train_data_dir: [
    'dataset/TextZoom/train1',
    'dataset/TextZoom/train2',
  ]
  batch_size: 32
  width: 128
  height: 32
  epochs: 500
  cuda: True
  ngpu: 2
  workers: 2
  # resume: './ckpt/vis/model_best.pth'
  resume: ''
  ckpt_dir: './ckpt/'
  voc_type: 'all' #'digits lower upper all'
  saveInterval: 200
  displayInterval: 100 #display loss
  adadelta: False
  lr: 0.001
  adam: True
  beta1: 0.5
  manualSeed: 1234
  max_len: 100
  keep_ratio: False
  down_sample_scale: 2
  loss_type: CRNNImagePercptualLoss # type:[ImageLoss, L1Loss, MSELoss, CRNNImagePercptualLoss]

  VAL:
    val_data_dir: [
      'dataset/TextZoom/test/hard',
      'dataset/TextZoom/test/easy',
      'dataset/TextZoom/test/medium',
    ]
    n_vis: 10
    vis_dir: 'demo'
    valInterval: 1000 #-1, val at the end of epoch
    rec_pretrained: 'demo.pth.tar'
    # moran_pretrained: 'moran.pth'
    # crnn_pretrained: 'crnn.pth'

TEST:
  checkpoint: ''
  test_data_dir: [
  ]

CONVERT:
  image_dir:
  lmdb_dir:
  n_convert: 10
